services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    env_file:
      - .env
    environment:
      DEV_MODE: "true"

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
    environment:
      VITE_API_URL: "http://backend:8000"
    depends_on:
      - backend
